import { define } from "gunshi"
import { fail } from "../error.ts"
import { handleChanges, handleCheck, handlePause, handleReceipt, handleRenew, handleResume, handleReview, handleTemplate, handleYearly } from "../features.ts"

function ids(ctx: { positionals: string[] }): number[] | undefined {
  const values = ctx.positionals.slice(1).map(Number)
  if (values.some((n) => !Number.isInteger(n) || n < 1)) { fail("IDs must be positive integers"); return undefined }
  return values.length ? values : undefined
}

export const pauseCommand = define({ name: "pause", description: "Pause subscriptions", args: { id: { type: "positional", array: true, required: false }, force: { type: "boolean", short: "f", description: "Skip confirmation" } }, run: (ctx) => handlePause(ids(ctx), ctx.values.force) })
export const resumeCommand = define({ name: "resume", description: "Resume paused or cancelled subscriptions", args: { id: { type: "positional", array: true, required: false }, force: { type: "boolean", short: "f", description: "Skip confirmation" } }, run: (ctx) => handleResume(ids(ctx), ctx.values.force) })

export const renewCommand = define({ name: "renew", description: "Renew a subscription", args: { id: { type: "positional", required: true }, price: { type: "string" }, currency: { type: "string" }, cycle: { type: "string" }, contractEnd: { type: "string" }, planTier: { type: "string" }, autoRenewal: { type: "boolean" } }, run: (ctx) => { const id = Number(ctx.values.id); if (!Number.isInteger(id) || id < 1) { fail("Valid subscription ID is required"); return }; return handleRenew(id, ctx.values) } })
export const reviewCommand = define({ name: "review", description: "Review upcoming renewals, bills, and trials", args: { billDays: { type: "string" }, contractDays: { type: "string" }, trialDays: { type: "string" }, json: { type: "boolean", short: "j" } }, run: (ctx) => handleReview({ billDays: ctx.values.billDays ? Number(ctx.values.billDays) : undefined, contractDays: ctx.values.contractDays ? Number(ctx.values.contractDays) : undefined, trialDays: ctx.values.trialDays ? Number(ctx.values.trialDays) : undefined, json: ctx.values.json }) })
export const yearlyCommand = define({ name: "yearly", description: "Show annual subscription spending", args: { year: { type: "string" }, currency: { type: "string", short: "c" }, json: { type: "boolean", short: "j" } }, run: (ctx) => { const year = ctx.values.year ? Number(ctx.values.year) : undefined; if (year !== undefined && (!Number.isInteger(year) || year < 1970 || year > 9999)) { fail("year must be a valid year"); return }; return handleYearly(year, ctx.values.currency, ctx.values.json) } })
export const checkCommand = define({ name: "check", description: "Check subscription data integrity", args: { strict: { type: "boolean", description: "Exit with code 1 when problems are found" }, json: { type: "boolean", short: "j" } }, run: (ctx) => handleCheck({ strict: ctx.values.strict, json: ctx.values.json }) })
export const changesCommand = define({ name: "changes", description: "Show subscription changes", args: { id: { type: "string" }, from: { type: "string" }, to: { type: "string" }, limit: { type: "string" }, json: { type: "boolean", short: "j" } }, run: (ctx) => handleChanges({ id: ctx.values.id ? Number(ctx.values.id) : undefined, from: ctx.values.from, to: ctx.values.to, limit: ctx.values.limit ? Number(ctx.values.limit) : undefined, json: ctx.values.json }) })
export const receiptCommand = define({ name: "receipt", description: "Import subscription candidates from a receipt file", args: { file: { type: "positional", required: true }, dryRun: { type: "boolean" }, review: { type: "boolean" }, json: { type: "boolean", short: "j" } }, run: (ctx) => handleReceipt(ctx.values.file, { dryRun: ctx.values.dryRun, review: ctx.values.review, json: ctx.values.json }) })

const templateListCommand = define({ name: "list", description: "List templates", run: () => handleTemplate("list") })
const templateArgs = { name: { type: "positional" as const, required: true }, price: { type: "string" as const }, currency: { type: "string" as const }, cycle: { type: "string" as const }, tags: { type: "string" as const }, billingDay: { type: "string" as const }, notes: { type: "string" as const }, paymentMethod: { type: "string" as const }, vendorName: { type: "string" as const }, vendorUrl: { type: "string" as const }, planTier: { type: "string" as const }, autoRenewal: { type: "boolean" as const } }
const templateAddCommand = define({ name: "add", description: "Add a template", args: templateArgs, run: (ctx) => handleTemplate("add", String(ctx.values.name), { price: ctx.values.price ? Number(ctx.values.price) : undefined, currency: ctx.values.currency ? String(ctx.values.currency) : undefined, cycle: ctx.values.cycle ? String(ctx.values.cycle) as never : undefined, tags: typeof ctx.values.tags === "string" ? ctx.values.tags.split(",").map((x) => x.trim()).filter(Boolean) : [], billingDay: ctx.values.billingDay ? Number(ctx.values.billingDay) : undefined }) })
const templateEditCommand = define({ name: "edit", description: "Edit a template", args: templateArgs, run: (ctx) => handleTemplate("edit", String(ctx.values.name), { price: ctx.values.price ? Number(ctx.values.price) : undefined, currency: ctx.values.currency ? String(ctx.values.currency) : undefined, cycle: ctx.values.cycle ? String(ctx.values.cycle) as never : undefined, tags: typeof ctx.values.tags === "string" ? ctx.values.tags.split(",").map((x) => x.trim()).filter(Boolean) : undefined, billingDay: ctx.values.billingDay ? Number(ctx.values.billingDay) : undefined }) })
const templateDeleteCommand = define({ name: "delete", description: "Delete a template", args: { name: { type: "positional", required: true } }, run: (ctx) => handleTemplate("delete", ctx.values.name) })
const templateUseCommand = define({ name: "use", description: "Add a subscription from a template", args: { name: { type: "positional", required: true }, price: { type: "string" }, currency: { type: "string" }, cycle: { type: "string" }, tags: { type: "string" } }, run: (ctx) => handleTemplate("use", ctx.values.name, { price: ctx.values.price ? Number(ctx.values.price) : undefined, currency: ctx.values.currency, cycle: ctx.values.cycle as never, tags: ctx.values.tags?.split(",").map((x: string) => x.trim()).filter(Boolean) }) })
export const templateCommand = define({ name: "template", description: "Manage subscription templates", subCommands: { list: templateListCommand, add: templateAddCommand, edit: templateEditCommand, delete: templateDeleteCommand, use: templateUseCommand }, run: () => handleTemplate("list") })
