name: scheduled-ci

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - run: pnpm build

      - name: Type check
        working-directory: ./subtrack
        run: pnpm lint:types

      - run: pnpm test
